### ISSUE TITLE
Full Serializer cause asset reimport when saving project.

### ISSUE THREAD

**Issue by YinXiaozhou** [jacobdufault/fullinspector#108]
I switched default serializer from Json.NET to Full Serializer since Json.Net can't serialize private property with [SerializedField]. 
Every thing work fine except every time I save my project, Unity will reimport some asset. That will take some time which is annoying. And the saving reimport never happen when I use Json.Net.

I'm using FI 2.5 on OSX.

**Comment by jacobdufault** [comment]
Can you send me an email? I think I know the cause of this issue and I can sent you a 2.6 build which should have fixed it.
