### ISSUE TITLE
Cannot show list of any type in Unity 5

### ISSUE THREAD

**Issue by YinXiaozhou** [jacobdufault/fullinspector#111]
My FI version is 2.5.
Get error at line 23 of RotorzGUIHelper.cs. Any ideas?

NullReferenceException: Object reference not set to an instance of an object
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
FullInspector.Rotorz.ReorderableList.Internal.RotorzGUIHelper+<RotorzGUIHelper>c__AnonStorey9.<>m__3E () (at Assets/FullInspector2/Modules/Collections/Rotorz/Editor/Internal/RotorzGUIHelper.cs:23)
FullInspector.Rotorz.ReorderableList.ReorderableListControl.PrepareState (Int32 controlID, IReorderableListAdaptor adaptor) (at Assets/FullInspector2/Modules/Collections/Rotorz/Editor/ReorderableListControl.cs:399)
FullInspector.Rotorz.ReorderableList.ReorderableListControl.Draw (Rect position, Int32 controlID, IReorderableListAdaptor adaptor, FullInspector.Rotorz.ReorderableList.DrawEmptyAbsolute drawEmpty) (at Assets/FullInspector2/Modules/Collections/Rotorz/Editor/ReorderableListControl.cs:1061)
FullInspector.Rotorz.ReorderableList.ReorderableListControl.DrawControlFromState (Rect position, IReorderableListAdaptor adaptor, FullInspector.Rotorz.ReorderableList.DrawEmptyAbsolute drawEmpty, ReorderableListFlags flags) (at Assets/FullInspector2/Modules/Collections/Rotorz/Editor/ReorderableListControl.cs:240)
FullInspector.Rotorz.ReorderableList.ReorderableListGUI.DoListFieldAbsolute (Rect position, IReorderableListAdaptor adaptor, FullInspector.Rotorz.ReorderableList.DrawEmptyAbsolute drawEmpty, ReorderableListFlags flags) (at Assets/FullInspector2/Modules/Collections/Rotorz/Editor/ReorderableListGUI.cs:218)
FullInspector.Rotorz.ReorderableList.ReorderableListGUI.ListFieldAbsolute (Rect position, IReorderableListAdaptor adaptor, FullInspector.Rotorz.ReorderableList.DrawEmptyAbsolute drawEmpty, ReorderableListFlags flags) (at Assets/FullInspector2/Modules/Collections/Rotorz/Editor/ReorderableListGUI.cs:227)
FullInspector.Internal.BaseCollectionPropertyEditor`4[System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][][],System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][][],System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][],System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][]].DoEdit (Rect region, UnityEngine.GUIContent label, System.Collections.Generic.KeyValuePair`2[][]& collection, FullInspector.fiGraphMetadata metadata, IReorderableListAdaptor adaptor) (at Assets/FullInspector2/Modules/Collections/Editor/BaseCollectionPropertyEditor.cs:153)
FullInspector.Internal.BaseCollectionPropertyEditor`4[System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][][],System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][][],System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][],System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][]].Edit (Rect region, UnityEngine.GUIContent label, System.Collections.Generic.KeyValuePair`2[][] collection, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Modules/Collections/Editor/BaseCollectionPropertyEditor.cs:401)
FullInspector.PropertyEditor`1[System.Collections.Generic.KeyValuePair`2[System.Single,UnityEngine.Sprite][][]].FullInspector.IPropertyEditorEditAPI.Edit (Rect region, UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditor.cs:62)
FullInspector.PropertyEditorExtensions.DoEdit2[Object] (IPropertyEditorEditAPI api, Rect region, UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:163)
FullInspector.PropertyEditorExtensions.DoEdit[Object] (IPropertyEditorEditAPI api, Rect region, UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:90)
FullInspector.PropertyEditorExtensions.Edit[Object] (IPropertyEditor editor, Rect region, UnityEngine.GUIContent label, System.Object element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:78)
FullInspector.Internal.fiEditorGUI.EditPropertyDirect (Rect region, FullInspector.InspectedProperty property, System.Object propertyValue, fiGraphMetadataChild metadataChild, System.Object context) (at Assets/FullInspector2/Core/Editor/fiEditorGUI.cs:218)
FullInspector.Internal.fiEditorGUI.EditProperty (Rect region, System.Object container, FullInspector.InspectedProperty property, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/fiEditorGUI.cs:228)
FullInspector.Internal.ReflectedPropertyEditor.EditProperty (UnityEngine.Rect& region, System.Object element, FullInspector.InspectedProperty property, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/ReflectedPropertyEditor.cs:158)
FullInspector.Internal.ReflectedPropertyEditor.EditPropertiesButtons (Rect region, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/ReflectedPropertyEditor.cs:248)
FullInspector.Internal.ReflectedPropertyEditor.Edit (Rect region, UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/ReflectedPropertyEditor.cs:300)
FullInspector.PropertyEditorExtensions.DoEdit2[Object] (IPropertyEditorEditAPI api, Rect region, UnityEngine.GUIContent label, UnityEngine.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:163)
FullInspector.PropertyEditorExtensions.DoEdit[Object] (IPropertyEditorEditAPI api, Rect region, UnityEngine.GUIContent label, UnityEngine.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:90)
FullInspector.PropertyEditorExtensions.Edit[Object] (IPropertyEditor editor, Rect region, UnityEngine.GUIContent label, UnityEngine.Object element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:78)
FullInspector.DefaultBehaviorEditor.OnEdit (Rect rect, UnityEngine.Object behavior, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/DefaultBehaviorEditor.cs:29)
FullInspector.BehaviorEditor`1[TBehavior].Edit (Rect rect, UnityEngine.Object behavior) (at Assets/FullInspector2/Core/Editor/IBehaviorEditor.cs:65)
FullInspector.IBehaviorEditorExtensions.EditWithGUILayout[Object] (IBehaviorEditor editor, UnityEngine.Object element) (at Assets/FullInspector2/Core/Editor/IBehaviorEditorExtensions.cs:22)
FullInspector.FullInspectorCommonSerializedObjectEditor.ShowInspectorForSerializedObject (UnityEngine.Object target) (at Assets/FullInspector2/Core/Editor/FullInspectorCommonSerializedObjectEditor.cs:152)
FullInspector.FullInspectorCommonSerializedObjectEditor.OnInspectorGUI () (at Assets/FullInspector2/Core/Editor/FullInspectorCommonSerializedObjectEditor.cs:172)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean forceDirty, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect, Boolean eyeDropperDirty) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1150)
UnityEditor.DockArea:OnGUI()

**Comment by YinXiaozhou** [comment]
I guess I fixed this problem.

I changed line 18-25
            var tyGUIClip = typeof(GUI).Assembly.GetType("UnityEngine.GUIClip");
            if (tyGUIClip != null) {
                var piVisibleRect = tyGUIClip.GetProperty("visibleRect", BindingFlags.Static | BindingFlags.Public);
                if (piVisibleRect != null) {
                    var getGetMethod = piVisibleRect.GetGetMethod();
                    VisibleRect = () => (Rect)getGetMethod.Invoke(null, null);
                }
            }

to 

	  VisibleRect = () => GUILayoutUtility.GetLastRect();

Then there's no error and every shows up.
I guess the orig code is trying to get the internal rect function. And versions later Unity opened that API.

**Comment by jacobdufault** [comment]
I've fixed the issue in 2.6 which is in the approval process in the asset store. Send me an email if you want the build now.

`GUIClip.visibleRect` relates to `GUI.BeginArea` and `GUI.EndArea`, whereas `GUILayoutUtility.GetLastRect` returns the most recently used rectangle by the gui layout system (which is not used in FI).

**Comment by khindemit** [comment]
I have the same error in trial version, can you fix that?
I want to try it and then buy.

**Comment by jacobdufault** [comment]
Can you send me an email? I'll push an update to the trial, but I don't know when yet.

**Comment by khindemit** [comment]
my email? k.hindemit@rambler.ru
