### ISSUE TITLE
older unity version support (4.3)

### ISSUE THREAD

**Issue by LasseLoepfe** [jacobdufault/fullinspector#117]
Hi,

is it possible to use fullinspector with Unity 4.3.7?

Best
Lasse

**Comment by jacobdufault** [comment]
Not anymore, but a pretty recent version (2.6.0?) supported 4.3.7. I can send you a build if you want (just send me an email first). I rewrote the serialization pipeline to take advantage of new Unity features introduced after 4.3.7 (I think that landed in 2.6.1) so unfortunately backporting is no longer viable. Can you target consoles using 5.0?

**Comment by LasseLoepfe** [comment]
Hi,
Nintendo will suport unity 5 but until then we are stuck with 4.3.7. I need to expose Dictionaries to the inspector. If that is possible in version 2.6.0 I would be very thankful if you could send me a copy.
Best
Lasse
P.s: On monday I can dig out the invoice number, if needed.




Am 13.06.2015 um 22:01 schrieb Jacob Dufault <notifications@github.com>:

**Comment by jacobdufault** [comment]
Okay, just send me an email and I'll reply with a build that should work on 4.3.7. I wish Unity actually did simultaneous releases for every platform.

**Comment by LasseLoepfe** [comment]
Hi,

I think the promelem is more on nintendos side, they test everyting twice.

My invoice number is: 301571375

I'd really apreciate if you could send me the 2.6.0 version to
lasse.loepfe@gmail.com

best
Lasse

**Comment by jacobdufault** [comment]
Please check your inbox, thanks!
