### ISSUE TITLE
UnityEvent<T0> doesn't seem to work

### ISSUE THREAD

**Issue by steamrollerstudios** [jacobdufault/fullinspector#120]
I've been using UnityEvents with full inspector for a while and they work perfectly. I tried to create a UnityEvent for which i could pass an argument, in this case bool, and I got an error when trying to display the inspector.

UnityEditor.PropertyHandler.GetHeight (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/Editor/Mono/ScriptAttributeGUI/PropertyHandler.cs:216)
UnityEditor.EditorGUI.GetPropertyHeightInternal (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/Editor/Mono/EditorGUI.cs:4796)
UnityEditor.EditorGUI.GetPropertyHeight (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label, Boolean includeChildren) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:746)
UnityEditor.EditorGUI.GetPropertyHeight (UnityEditor.SerializedProperty property, UnityEngine.GUIContent label) (at C:/buildslave/unity/build/artifacts/generated/common/editor/EditorGUIBindings.gen.cs:734)
FullInspector.Internal.fiGenericPropertyDrawerPropertyEditor`2[TContainer,T].DoPropertyFieldHeight (FullInspector.Internal.ItemMetadata metadata, UnityEngine.GUIContent label, .T item) (at Assets/FullInspector2/Core/Editor/PropertyEditors/fiGenericPropertyDrawerPropertyEditorManager.cs:51)
FullInspector.Internal.fiGenericPropertyDrawerPropertyEditor`2[TContainer,T].GetElementHeight (UnityEngine.GUIContent label, .T element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/fiGenericPropertyDrawerPropertyEditorManager.cs:81)
FullInspector.PropertyEditor`1[TElement].FullInspector.IPropertyEditorEditAPI.GetElementHeight (UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditor.cs:82)
FullInspector.PropertyEditorExtensions.GetElementHeight[Object] (IPropertyEditor editor, UnityEngine.GUIContent label, System.Object element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:240)
FullInspector.Internal.AttributePropertyEditor.GetElementHeight (UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/AttributePropertyEditor.cs:113)
FullInspector.PropertyEditorExtensions.GetElementHeight[Object] (IPropertyEditor editor, UnityEngine.GUIContent label, System.Object element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:240)
FullInspector.Internal.fiEditorGUI.EditPropertyHeightDirect (FullInspector.InspectedProperty property, System.Object propertyValue, fiGraphMetadataChild metadataChild) (at Assets/FullInspector2/Core/Editor/fiEditorGUI.cs:346)
FullInspector.Internal.fiEditorGUI.EditPropertyHeight (System.Object container, FullInspector.InspectedProperty property, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/fiEditorGUI.cs:351)
FullInspector.Internal.ReflectedPropertyEditor.GetElementHeight (UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/ReflectedPropertyEditor.cs:415)
FullInspector.PropertyEditorExtensions.GetElementHeight[Object] (IPropertyEditor editor, UnityEngine.GUIContent label, UnityEngine.Object element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:240)
FullInspector.DefaultBehaviorEditor.OnGetHeight (UnityEngine.Object behavior, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/DefaultBehaviorEditor.cs:47)
FullInspector.BehaviorEditor`1[TBehavior].GetHeight (UnityEngine.Object behavior) (at Assets/FullInspector2/Core/Editor/IBehaviorEditor.cs:89)
FullInspector.IBehaviorEditorExtensions.EditWithGUILayout[Object] (IBehaviorEditor editor, UnityEngine.Object element) (at Assets/FullInspector2/Core/Editor/IBehaviorEditorExtensions.cs:19)
FullInspector.FullInspectorCommonSerializedObjectEditor.ShowInspectorForSerializedObject (UnityEngine.Object target) (at Assets/FullInspector2/Core/Editor/FullInspectorCommonSerializedObjectEditor.cs:145)
FullInspector.FullInspectorCommonSerializedObjectEditor.OnInspectorGUI () (at Assets/FullInspector2/Core/Editor/FullInspectorCommonSerializedObjectEditor.cs:161)
UnityEditor.InspectorWindow.DrawEditor (UnityEditor.Editor editor, Int32 editorIndex, Boolean forceDirty, System.Boolean& showImportedObjectBarNext, UnityEngine.Rect& importedObjectBarRect, Boolean eyeDropperDirty) (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1162)
UnityEditor.DockArea:OnGUI()

**Comment by jacobdufault** [comment]
I'm unable to reproduce this. I tested with

```c#
public struct Wrap {
    public UnityEvent<bool> boolEvent;
    public UnityEvent<int, int> intEvent;
}
public class Test : BaseBehavior {
    public Wrap wrap;
    public UnityEvent<bool> boolEvent;
}
```

What version of Unity are you on? Can you give more repro instructions (code sample)?

**Comment by jacobdufault** [comment]
Can you also please try deleting `FullInspector2_Generated/PropertyDrawerIntegration`? Perhaps something got corrupted.

**Comment by steamrollerstudios** [comment]
From what i understand, you have to subclass the Generic UnityEvent cause its an abstract class. Maybe that's it. Ill work on a test case.

**Comment by steamrollerstudios** [comment]
Yeah I'm getting it with this bit of code:

```c#
using FullInspector;
using UnityEngine.Events;

public class BoolEvent : UnityEvent<bool>
{
}

public class Test : BaseBehavior
{
    public BoolEvent boolEvent;
}
```

**Comment by jacobdufault** [comment]
Please change `BoolEvent` to be serializable, ie:

```
[Serializable]
public class BoolEvent : UnityEvent<bool> {}
```

The property drawer integration relies on the property drawer that Unity ships for `UnityEvent`. If `BoolEvent` is not serializable, then Unity will refuse to draw the property drawer.

You can also just use `UnityEvent<bool>` :)

**Comment by jacobdufault** [comment]
I've added an error message to the console for when this happens, notifying the user to add a `[Serializable]` annotation.
