### ISSUE TITLE
First item not added to list via button

### ISSUE THREAD

**Issue by steamrollerstudios** [jacobdufault/fullinspector#121]
I have boiled down a bug into a simple repo case:

Foo.cs
```c#
using FullInspector;
using System.Collections.Generic;
using UnityEngine;

public class Foo : BaseBehavior
{
    public List<Bar> bars;

    [InspectorButton]
    public Bar AddBar()
    {
        var _gameObject = new GameObject();
        _gameObject.transform.parent = transform;

        var _bar = _gameObject.AddComponent<Bar>();
        bars.Add( _bar );

        return _bar;
    }
}
```

Bar.cs
```c#
using FullInspector;

public class Bar : BaseBehavior
{
}
```
In this example, when you add Foo to a game object, there is an "Add Bar" button. When you click on it, it will run the code within, but the list will remain empty. The game object will be created but not added to the list. If you hit it again, another object will be created but this time it will be added to the list.

I've tried to initializing the bars variable in the declaration and via a reset method but neither seem to fix the problem.

**Comment by jacobdufault** [comment]
How strange. Later tonight or tomorrow I'll be able to take a deeper look into the issue. It also happens when you just press the 'add' item button in the list editor itself.

If you reply with your email address or send me an email, then I'll send you a fixed build when I fix the issue.

**Comment by steamrollerstudios** [comment]
Thanks! That will be awesome. My email is keith@steamrollerstudios.com.

**Comment by jacobdufault** [comment]
Can you change FullInspector2\Core\fiISerializedObjectUtility.cs line 177ish (right above the `return success`) to

```c#
obj.IsRestored = true;
return success;
```

I can also send you a build.

Let me know if that fixes it, thanks!

**Comment by steamrollerstudios** [comment]
I tried this but didn't seem to change anything on my end.

**Comment by jacobdufault** [comment]
Ok, I've sent a build to you - can you see if that one resolves the issue? Thanks

**Comment by steamrollerstudios** [comment]
It works! Cheers for fixing this
