### ISSUE TITLE
Visual bug with dictionaries

### ISSUE THREAD

**Issue by sarkahn** [jacobdufault/fullinspector#122]
Having a weird visual bug where removing an element from the middle of a dictionary which uses > 1 line values causes some really annoying overlap that makes it impossible to keep working. It seems to be purely visual but the only way to fix it is to enter/exit play mode.

Example: http://gfycat.com/ExcellentMammothBooby

Code I was using to reproduce:

```
public class DictHaver : FullInspector.BaseBehavior
{
    public Dictionary<string, DumbStruct> dict_;

    public struct DumbStruct
    {
        public int i_;
        public string str_;
        public List<int> ints_;
    }
 }
```

**Comment by jacobdufault** [comment]
Okay, thanks - this looks like some metadata is getting corrupted. I'll be able to take a look in a few days.

**Comment by jacobdufault** [comment]
Can you try changing fiGraphMetadata.cs line 260 from

```c#
copiedGraphs.Add(metadata._childrenInt[i]);
```

to

```c#
copiedGraphs.Add(metadata._childrenInt[migrations[i].OldIndex]);
```

Thanks

**Comment by sarkahn** [comment]
Just tried it. Appears to have fixed the issue, thanks!

**Comment by jacobdufault** [comment]
Awesome! Thanks
