### ISSUE TITLE
Should not be able to drag Game Object from scene into prefab

### ISSUE THREAD

**Issue by Ghopper21** [jacobdufault/fullinspector#123]
With purchased v2.6.2, I am able to drag a game object from the scene into a prefab public GameObject field on a BaseBehavior, which is misleading because when I reload the scene, the prefab's member field is set back to None.

On the contrary, Unity's normal Inspector behavior for MonoBehaviours is to NOT allow you to drag a game object into a prefab. That should what Full Inspector does also. (Unless the intended behavior is to allow prefabs to hold references to in-scene game objects, in which case the bug here is that the reference is not being saved.)

**Comment by jacobdufault** [comment]
I'll look into this in a few days, but it may be a bug on Unity's end with EditorGUI.ObjectField - maybe I can work around it.

**Comment by Ghopper21** [comment]
Cool thanks.

**Comment by jacobdufault** [comment]
Fixed, I'll PM you a corrected build in the next 30 minutes or so. Thanks!
