### ISSUE TITLE
Scriptable Assets don't show name of asset

### ISSUE THREAD

**Issue by steamrollerstudios** [jacobdufault/fullinspector#126]
I'm using a variation of a script on the [Unity Wiki](http://wiki.unity3d.com/index.php?title=CreateScriptableObjectAsset) to create assets out of our scriptable objects. When i want to reference one of those assets in a script via the inspector, it shows the name of the scriptable object instead of the name of the asset. This makes it really hard to tell the difference between different references when you have a list of these objects on your class because they all have the same name. 

Here is an image of what im seeing in the inspector:

https://s3.amazonaws.com/uploads.hipchat.com/143523/1038333/W12xlMjYMqkHfLp/upload.png

As you can see the Resources says "Resource" instead of the name of the asset (eg. Wood, Metal, ect)

I hope this is clear explanation. Let me know if you need more details.

**Comment by steamrollerstudios** [comment]
For some reason this has started working. Not sure why... anyways, carry on.

**Comment by jacobdufault** [comment]
Closing since it is now working.
