### ISSUE TITLE
Show referenced component name in ObjectField of SerializedAction

### ISSUE THREAD

**Issue by YinXiaozhou** [jacobdufault/fullinspector#130]
I know the ObjectField of Unity only shows the name of the GameObject. This could be confusing when the reference is link to a specific component on the GO. Especially when I'm editing a list of SerializedActions. 

So I managed to draw the name of the referenced component on the ObjectFied of SerializedAction by adding code below to **line 99 in BaseSerializationDelegateEditor.cs**.
```
			if(element.MethodContainer)
			{
				// Draw the refenreced component on the ObjectField
				Vector2 size = EditorStyles.objectField.CalcSize(new GUIContent(element.MethodContainer.name));
				objectRect.x += size.x - 8f;
				objectRect.width -= size.x + 10f;
				GUI.Label(objectRect, "->" + element.MethodContainer.GetType());
			}
```
Result is like this,
![screen shot 2015-09-22 at 3 30 36 pm](https://cloud.githubusercontent.com/assets/3391696/10012895/ed35ac0e-613e-11e5-8515-ad53c3d7f653.png)

It's pretty hacking and hardcoding but it works. Maybe you want to refine it and apply it to all ObjectField by making a wrap function of ObjectField().

**Comment by jacobdufault** [comment]
Ah! This is brilliant! I've always wanted to improve the object field to show the component name. Thanks! This will be in the next access build.

**Comment by jacobdufault** [comment]
![image](https://cloud.githubusercontent.com/assets/356714/13040287/367b2a14-d35f-11e5-8254-a03644118259.png)
