### ISSUE TITLE
Should use SceneManager

### ISSUE THREAD

**Issue by nykwil** [jacobdufault/fullinspector#133]
Assets/FullInspector2/Modules/SerializerMigrationUtility/Editor/fiSerializerMigrationUtilityEditorWindow.cs(236,43): warning CS0618: `UnityEditor.EditorApplication.OpenScene(string)' is obsolete: `Use EditorSceneManager.OpenScene'
Assets/FullInspector2/Modules/SerializerMigrationUtility/Editor/fiSerializerMigrationUtilityEditorWindow.cs(240,43): warning CS0618: `UnityEditor.EditorApplication.currentScene' is obsolete: `Use EditorSceneManager to see which scenes are currently loaded'

**Comment by jacobdufault** [comment]
Thanks, this has been fixed in the latest master. You can download a new version of FI at http://jacobdufault.github.io/fullinspector/access/.
