### ISSUE TITLE
Embedding a Full Inspector Editor

### ISSUE THREAD

**Issue by nykwil** [jacobdufault/fullinspector#134]
Embedding a Full Inspector Editor example doesn't work, just tested the first two parts (http://jacobdufault.github.io/fullinspector/guide/#docs/usage_embedding)

NullReferenceException: Object reference not set to an instance of an object
FullInspector.Internal.ReflectedPropertyEditor.HasLabel (UnityEngine.GUIContent label) (at Assets/FullInspector2/Core/Editor/PropertyEditors/ReflectedPropertyEditor.cs:81)
FullInspector.Internal.ReflectedPropertyEditor.GetElementHeight (UnityEngine.GUIContent label, System.Object element, FullInspector.fiGraphMetadata metadata) (at Assets/FullInspector2/Core/Editor/PropertyEditors/ReflectedPropertyEditor.cs:338)
FullInspector.PropertyEditorExtensions.GetElementHeight[MyType] (IPropertyEditor editor, UnityEngine.GUIContent label, .MyType element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:256)
FullInspector.PropertyEditorExtensions.EditWithGUILayout[MyType] (IPropertyEditor editor, UnityEngine.GUIContent label, .MyType element, fiGraphMetadataChild metadata) (at Assets/FullInspector2/Core/Editor/IPropertyEditorExtensions.cs:306)
EmbedDemo.OnGUI () (at Assets/Editor/FullTestEditor.cs:26)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at

**Comment by jacobdufault** [comment]
Thanks, I've updated the sample to fix the error.
