### ISSUE TITLE
Using GUILayout / EditorGUILayout in custom editors raises errors

### ISSUE THREAD

**Issue by toumorokoshi** [jacobdufault/fullinspector#140]
Hi,

I'm trying to write a custom property editor for a FullInspector property. I've been able to use GUI and EditorGUI just fine, but when I try to use any GUILayout or EditorGUILayout items, I get:

`
Severity	Code	Description	Project	File	Line	Suppression State
Error		ArgumentException: Getting control 2's position in a group with only 2 controls when doing Repaint
Aborting	Solution 'cerebrawl' ‎(3 projects)	C:/buildslave/unity/build/Runtime/IMGUI/Managed/GUILayoutUtility.cs	656	
`

Some googling shows that it's caused by a change of data state in between the Layout event and the Repaint event:

http://answers.unity3d.com/questions/400454/argumentexception-getting-control-0s-position-in-a-1.html

    [CustomPropertyEditor(typeof(StateMachine2))]
    public class StateMachine2Editor : PropertyEditor<StateMachine2>
    {
        protected ScrollableList<State2> list = new ScrollableList<State2>();
    
        public override StateMachine2 Edit(Rect region, GUIContent label, StateMachine2 element, fiGraphMetadata metadata)
        {
            // element.States.Sort();
            var listRegion = new Rect(region.x, region.y, region.width * 0.2f, region.height);
            var selectedState = list.Draw(element.States, listRegion);
            // body
            /* var bodyRegion = new Rect(region.x + region.width * 0.22f, region.y,
                                      region.width * 0.78f, region.height);
            DrawBody(bodyRegion, selectedState, metadata); */
            return element;
        }
    
        protected void DrawBody(Rect region, State2 selected, fiGraphMetadata metadata)
        {
            var editorChain = PropertyEditor.Get(typeof(State2), null);
            IPropertyEditor editor = editorChain.SkipUntilNot(
                    typeof(FullInspector.Modules.Common.IObjectPropertyEditor),
                    typeof(FullInspector.Internal.AbstractTypePropertyEditor)
            );
            var childMetadata = metadata.Enter("State2Editor");
            if (selected != null)
            {
                editor.Edit(region, new GUIContent("State"), selected, childMetadata);
            }
            // EditorGUI.HelpBox(region, "Hello, this is a custom after section.", MessageType.Info);
            // selected;
        }
    }

My property editor is completely empty except for the EditorGUILayout function. Is it possible to use GUILayout / EditorGUILayout with fullinspector?

**Comment by jacobdufault** [comment]
Sorry, the *Layout functions are not available in `PropertyEditors`. They are available in `BehaviorEditor` though.

As an alternative, I've written the [toolkit](http://jacobdufault.github.io/fullinspector/guide/#docs/extending_toolkit) which is (in my opinion) easier to use since it's far more declarative. You also usually don't even have to write the `PropertyEditor` - you extend the type directly. This helps make sure that your editor and type stay in-sync.

**Comment by lazlo-bonin** [comment]
It seems they are not working in BehaviorEditors either, which is annoying. The Toolkit isn't a viable option when you need your editor to reference classes that are only in the editor project.
