### ISSUE TITLE
InspectorShowIf/InspectorHideIf attributes for multiple properties

### ISSUE THREAD

**Issue by marek-mayer** [jacobdufault/fullinspector#142]
It would be great if it would be possible to use multiple proprties to be able to show/hide other properties if every single one of the properties is true (so this would be a logical AND). Or even go further and allow an OR with something like that:

```c#
public bool Cond1;
public bool Cond2;

[InspectorShowIf(LogicalOperators.OR, "Cond1", "Cond2")]
public string ShowIfAnyConditionTrue;

[InspectorShowIf(LogicalOperators.AND, "Cond1", "Cond2")]
public string ShowIfEveryConditionTrue;

```

**Comment by jacobdufault** [comment]
Done; this is available in the latest build from access. `LogicalOperators` is renamed to `fiLogicalOperators`.
