### ISSUE TITLE
Node Lock

### ISSUE THREAD

**Issue by steamrollerstudios** [jacobdufault/fullinspector#144]
So we are running into an issue where once we create a prefab we are no longer able to change any of the values including moving the game object around. In this case its a component which has a variable which points to a serializable class which has a game object as a variable.

Attached is a super simple project which demos the problem.
NodeLock.zip (removed)

There is a Test scene with a test object. if you grab it and try and move it, It wont. You can also not type in any attributes.

Please advise.

**Comment by steamrollerstudios** [comment]
To add, If we break the prefab connection, make changes then apply them back to the prefab... this work and is our current work around... which sucks.

**Comment by jacobdufault** [comment]
Thanks, I've downloaded the project and I will try to reproduce tonight.

**Comment by steamrollerstudios** [comment]
How we looking?

**Comment by jacobdufault** [comment]
I'm having trouble reproducing on 5.3.4p6. Can you try reproducing on that version? Or maybe I'm reproing wrong. Here's what I did:

I added a new object, added a `Test` component, added an element to the array. Then I made the object a prefab. I was still able to drag the object around in the scene hierarchy view after doing that.

**Comment by steamrollerstudios** [comment]
Those are the same steps we are doing here. So you were able to drag the object around the scene right? not the scene hierarchy?

**Comment by jacobdufault** [comment]
I didn't check dragging around the scene, let me try that.

**Comment by jacobdufault** [comment]
I've found the issue, but I believe this is a regression introduced by Unity. I've submitted a bug to them (https://fogbugz.unity3d.com/default.asp?818240_m622mv347ksj8nl6). For the time being, you should be able to work around by adding `[NotSerialized]` to the `UnityEvent` type.

**Comment by jacobdufault** [comment]
I've uploaded a new build to access that should work around the Unity bug.
