### ISSUE TITLE
Issue removing fullInspector

### ISSUE THREAD

**Issue by CostelloNicho** [jacobdufault/fullinspector#146]
After removing full inspector from my project I have a bunch of ghost transforms with missing Behaviours. I get about 30 different logs. 

1. The referenced script on this Behaviour is missing!
2. The referenced script on this Behaviour (Game Object 'fiPersistentEditorStorage') is missing!
...

When I double click on the message It takes me to an fiPersistentEditorStorage Object that does not exist in the hierarchy or project pane. I've deleted both directories ( including the generated directory ).

I tried reinstalling fullInspector and through the interface deleted all meta data and deleting all serialized data. 

I don't know what else to do. This is really starting to bother me.

**Comment by jacobdufault** [comment]
I'm not sure. If you double click the messages does it take you to the objects with the metadata? There should only be 2-3 hidden objects.

**Comment by jacobdufault** [comment]
These behaviors should be cleaned up automatically now by FI.

**Comment by haraldreingruber** [comment]
I think the issue is still present. @jacobdufault could you provide some hints how to clean up the scene/project manually? Thanks a lot.

**Comment by SugoiDev** [comment]
@haraldreingruber I would recommend that you add back FullInspector and use the **View All Scene GameObjects** editor window to delete the fi\* objects in each scene (need to open the scenes).
You can find that in **Window/Full Inspector/Developer/View All Scene GameObjects**

There'll be fiPersistentEditorStorage and fiGradientStorage, if I recall correctly. There  might be others I'm forgetting, but they'll all begin with fi\*.

I also recommend you use the latest FullInspector from github, as it will have an improved editor window for listing the scene objects.

**Comment by haraldreingruber** [comment]
Thanks. It worked.
