### ISSUE TITLE
When there is a compiler error in other scripts, Full Inspector FullSerialzer will fail to serialize classes and lose data.

### ISSUE THREAD

**Issue by Disastercake** [jacobdufault/fullinspector#150]
I've been having a problem for a while now that has been hurting productivity by deleting object references and scrambling text as hexidecimals in Full Inspector editors.  I've noticed this seems to recur commonly if there is a compiler build error in other scripts.  After the build compiles to the point of reaching the error.  This causes Full Inspector to throw an error in the debug log that it can't serialize the classes, and then it starts scrambling the data in the inspector fields.

An example of a string being scrambled:
Original:
MithosMeetsElise

Scrambled:
4d6974686f7353656573576172736869704f766572447261676f6e7472656556696c6c616765

Something strange about this is that it doesn't happen for everything everytime.  It seems rather sporadic whether it will scramble a field or lose reference to other objects.

**Comment by jacobdufault** [comment]
I have a feeling this is a Unity bug. What version are you on?

**Comment by Disastercake** [comment]
I just updated to the latest version and it did seem to get rid of the bug
actually!  I'll report back if it happens again.  Thank you!

-Mike Gale (Disastercake), creator of Soul Saga.

Website <http://www.disastercake.com> : Twitter
<https://twitter.com/disastercake> : Facebook
<https://www.facebook.com/disastercake>

**Comment by jacobdufault** [comment]
Great! Thanks.
