### ISSUE TITLE
InspectorTextArea not working as expected

### ISSUE THREAD

**Issue by grofie** [jacobdufault/fullinspector#153]
Hi Jacob,

great plugin but I have a little issue with it. Using the InspectorTextArea attribute is quite a shot in the leg: Since the string is only drawn into a single line, it is as useless a normal single line input field but takes muuch more space.

So its basically missing the scroll functionality. The height parameter is not really practically as well, the default unity3d attribute uses min and max lines number too!

Cheers,
Fiete

**Comment by jacobdufault** [comment]
Unfortunately there's not a whole lot I can do here without reimplementing Unity's text drawing editor components. `[TextArea]` uses a bunch of private methods that are not available.

I've not had any luck with their text wrapping logic working, either. `GUIStyle` and the like are just buggy.

I've added a `Lines` parameter that will do an automatic height computation for you. I'll upload a build to access that includes the change.

**Comment by grofie** [comment]
Hi Jacob,

thank you for your fast answer. Sorry, but the lines parameter alone wont help anything. The attribute like it is is totally useless. What to change the height for when i cannot see more text?

In my opinion, when you cannot make it right, better remove this attribute. It makes wrong hope and pisses people off when they see the results..

Cheers
