### ISSUE TITLE
Multiselected objects: Enum values are not applied!

### ISSUE THREAD

**Issue by grofie** [jacobdufault/fullinspector#154]
Hi Jacob, this one is much more serious:

1. Select multiple game objects with the same BaseBehavior script. 
2. Change an ENUM property
3. Select a single one of these objects
4. The enum value was not applied

This really fu**s up our workflow and brings a lot of mistakes. Please fix it asap. Thanks allot.

**Comment by jacobdufault** [comment]
FYI, multi-edit is still very buggy and not yet complete. I'm probably going to put it behind a flag.

**Comment by jacobdufault** [comment]
I've put it behind the `fiSettings.EnableMultiEdit` flag.

**Comment by jacobdufault** [comment]
This should be fixed in the next build.
