### ISSUE TITLE
Option to disable per-hierarchy-level InspectorOrder

### ISSUE THREAD

**Issue by lazlo-bonin** [jacobdufault/fullinspector#159]
I often find myself needing to mix orders of fields between child and parent classes, and FI doesn't allow it. The only workaround I found so far is terribly ugly:

```
class Base : BaseBehavior
{
    [HideInInspector]
    public int field;
}

class Child : Base
{
    [ShowInInspector, InspectorName("Field"), InspectorOrder(X)]
    public int inspectorField
    {
         get { return field; }
         set { field = value; }
    }
}
``` 

Is there a simple hotfix I could apply directly to the source to disable the ordering context?

**Comment by jacobdufault** [comment]
I've added a new `fsConfig.EnableGlobalOrdering` option that will unconditionally enable global ordering.

It defaults to false to maintain original behavior.

**Comment by jacobdufault** [comment]
For a hotfix, on InspectedType.cs line 268 add

```
StableSort(_allMembers, (a, b) => {
    double orderA = InspectorOrderAttribute.GetInspectorOrder(a.MemberInfo);
    double orderB = InspectorOrderAttribute.GetInspectorOrder(b.MemberInfo);
    return Math.Sign(orderA - orderB);
});
```
