### ISSUE TITLE
Tooltip description for the Script Name property

### ISSUE THREAD

**Issue by marek-mayer** [jacobdufault/fullinspector#161]
It would be great to have a virtual property in BaseBehavior, which I could override

```c#
protected override string ScriptDescription { 
 get  { return "This is a description for the inspector."; } 
}
```

and the string would be the tooltip of the Script Name property in the inspector.

**Comment by jacobdufault** [comment]
Which property are you referring to exactly? I'm not quite sure what you mean by Script Name.

I'm guessing you mean this one:

![image](https://cloud.githubusercontent.com/assets/356714/17238329/a8d41594-550f-11e6-9c1a-5355817a06c4.png)

**Comment by jacobdufault** [comment]
Done. It will now appear when you hover over "Script". Simply add `[InspectorTooltip]` to the class definition, ie,

```c#
[InspectorTooltip("Hello world!")]
public class PropertyTest : BaseBehavior {
  // ...
}
```
