### ISSUE TITLE
Question: Should the 'generated' folder be checked into version control?

### ISSUE THREAD

**Issue by hymerman** [jacobdufault/fullinspector#178]
Currently everyone on my team is constantly editing fiBackupStorage and fiPersistentEditorStorage, which means they have to be careful not to check in changes to these files else there may be conflicts. It looks like these can be ignored safely. Can the generated source also be ignored? At what point does it get generated? Will a command line batch build succeed if the generated source doesn't exist before Unity is invoked?

**Comment by jacobdufault** [comment]
Some of the generated files are needed for Unity to serialize assets properly. All of the cs files should be checked in, but none of the prefabs or scriptable objects.

**Comment by hymerman** [comment]
Great - thanks :)
