### ISSUE TITLE
Editor Application Not Responding After Script Save

### ISSUE THREAD

**Issue by Soren025** [jacobdufault/fullinspector#65]
My Unity application freezes and does not recover from the "Not Responding" state in task manager after saving scripts and unity re compiles.

This happened twice and I am unsure the cause but in both cases the only noticeable thing in common with both instances was that I had an inspector window displaying a struct that I have made.

The struct contains various properties that all manipulate 3 floats in the background in different ways. While it works changing one property value in the inspector also changes at least 80% of the other property values displayed.

Perhaps it is an unexpected infinite loop during serialization because of structure of my struct?

**Comment by jacobdufault** [comment]
Closing, no good solution in general for this issue.
