### ISSUE TITLE
UnityEvent / UnityAction in 4.6

### ISSUE THREAD

**Issue by miniscruff** [jacobdufault/fullinspector#92]
I know it is just the beta but are there plans to support the new UnityEvent ( which as i can tell is a list of UnityActions ). I have looked into it and i see no editor gui or editor function for this new system that is public and the rendering of the UnityEvent using a BaseBehavior over MonoBehavior isnt very helpful. I would like to use FullInspector for all my scripts but the new UnityEvents are an integral part and I would like to be able to use them. 

Just wondering if you had any plans really

**Comment by jacobdufault** [comment]
This will be included with the automatic property drawer integration.
