### ISSUE TITLE
GUIStyle is not being serialized, resets on play

### ISSUE THREAD

**Issue by yusefnapora** [jacobdufault/fullinspector#93]
I'm having an issue where a GUIStyle field attached to a BaseBehavior is getting completely reset whenever I press "Play".  All properties of the GUIStyle revert back to their default values.

A quick example class:

```csharp
    public class TestInspectorBug : BaseBehavior {
        public GUIStyle Style;
    }
```

Any changes made to the Style field of this component are immediately lost on Play.  Changing the class to a MonoBehavior fixes this, but obviously loses the benefit of Full Inspector.

I am using FullInspector 2.4 with FullSerializer, currently targeting iOS.

Edit:
Just to quickly follow up, making a Backup of the component doesn't work either.  All the fields of the backup's GUIStyle field are set to the defaults.

**Comment by jacobdufault** [comment]
I've added inspector support and Full Serializer support, but this will not work inside of the inspector because Unity throws exceptions when accessing GUIStyle instance members off the main thread.
